artista_all:
    path: /artist/
    defaults: { _controller: AppBundle:Artistas:getAllArtistas }
    methods:  [GET]
    
artista_get:
    path: /artist/{id}/
    defaults: { _controller: AppBundle:Artistas:getArtista }
    methods:  [GET]
    
artista_create:
    path: /artist/
    defaults: { _controller: AppBundle:Artistas:addArtista }
    methods:  [POST]
    
artista_update:
    path: /artist/{id}/
    defaults: { _controller: AppBundle:Artistas:updateArtista }
    methods:  [PUT]
    
artista_delete:
    path: /artist/{id}/
    defaults: { _controller: AppBundle:Artistas:deleteArtista }
    methods:  [DELETE]
    
artista_album:
    path: /artist/album/{idArtista}/
    defaults: { _controller: AppBundle:Artistas:setAlbumArtista }
    methods:  [PUT]

album_all:
    path: /album/
    defaults: { _controller: AppBundle:Albumes:getAllAlbums }
    methods:  [GET]

album_get:
    path: /album/{id}/
    defaults: { _controller: AppBundle:Albumes:getAlbum }
    methods:  [GET]
    
album_create:
    path: /album/
    defaults: { _controller: AppBundle:Albumes:addAlbum }
    methods:  [POST]
    
album_update:
    path: /album/{id}/
    defaults: { _controller: AppBundle:Albumes:updateAlbum }
    methods:  [PUT]
    
album_delete:
    path: /album/{id}/
    defaults: { _controller: AppBundle:Albumes:deleteAlbum}
    methods:  [DELETE]
    
album_artista:
    path: /album/artista/{idAlbum}/
    defaults: { _controller: AppBundle:Albumes:setArtistaAlbum }
    methods:  [PUT]